blank_issues_enabled: false

contact_links:
  - name: Contact the maintainer
    url: mailto:your_email@your_domain.com
    about: If your question is not an issue or PR, then by all means feel free to contact me directly.