name: Feature request
description: Suggest an improvement or new capability in YOUR_PROJECT_NAME
title: "[Feature] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! Help us improve YOUR_PROJECT_NAME.

  - type: textarea
    id: feature
    attributes:
      label: Feature description
      placeholder: What would you like to see added or changed?
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use case
      placeholder: Describe a scenario where this feature is useful